#ifndef SQLMANAGER_CAT_H
#define SQLMANAGER_CAT_H


/****************************************************************************/


/* This file was created automatically by CatComp.
 * Do NOT edit by hand!
 */


#ifndef EXEC_TYPES_H
#include <exec/types.h>
#endif

#ifdef CATCOMP_ARRAY
#ifndef CATCOMP_NUMBERS
#define CATCOMP_NUMBERS
#endif
#ifndef CATCOMP_STRINGS
#define CATCOMP_STRINGS
#endif
#endif

#ifdef CATCOMP_BLOCK
#ifndef CATCOMP_STRINGS
#define CATCOMP_STRINGS
#endif
#endif


/****************************************************************************/


#ifdef CATCOMP_NUMBERS

#define MSG_ERROR 1000
#define MSG_OK 1001
#define MSG_SAVE 1002
#define MSG_USE 1003
#define MSG_CANCEL 1004
#define MSG_ABORT 1005
#define MSG_ADD 1006
#define MSG_REMOVE 1007
#define MSG_SORT 1008
#define MSG_YESNO 1009
#define MSG_YESNOCANCEL 1010
#define MSG_ERROR_LOADING_ODBC 1011
#define MSG_CONNECT_DSN 1012
#define MSG_SELECT_DSN 1013
#define MSG_ENTER_CREDENTIALS 1014
#define MSG_USERNAME 1015
#define MSG_PASSWORD 1016
#define MSG_DSN_MANAGER 1017
#define MSG_BUTTON_CONNECT 1018
#define MSG_BUTTON_CANCEL 1019
#define MSG_ERROR_LISTING_TABLES 1020
#define MSG_ERROR_LAUNCHING_IODBC 1021
#define MSG_MENU_FILE 1022
#define MSG_MENU_NEW 1023
#define MSG_MENU_LOAD_FILE 1024
#define MSG_MENU_SAVE 1025
#define MSG_MENU_SAVE_AS 1026
#define MSG_MENU_ABOUT 1027
#define MSG_MENU_EXIT 1028
#define MSG_MENU_EDIT 1029
#define MSG_MENU_UNDO 1030
#define MSG_MENU_REDO 1031
#define MSG_MENU_CUT 1032
#define MSG_MENU_COPY 1033
#define MSG_MENU_PASTE 1034
#define MSG_MENU_QUERY 1035
#define MSG_MENU_EXECUTE_QUERY 1036
#define MSG_MENU_STOP_QUERY 1037
#define MSG_MENU_SHOW_RESULTS 1038
#define MSG_MENU_SHOW_AS_GRID 1039
#define MSG_MENU_SHOW_AS_TEXT 1040
#define MSG_MENU_SAVE_AS_TEXT 1041
#define MSG_MENU_SAVE_AS_XML 1042
#define MSG_SB_BUTTON_NEW 1043
#define MSG_SB_BUTTON_OPEN 1044
#define MSG_SB_BUTTON_SAVE 1045
#define MSG_SB_BUTTON_CUT 1046
#define MSG_SB_BUTTON_COPY 1047
#define MSG_SB_BUTTON_PASTE 1048
#define MSG_SB_BUTTON_UNDO 1049
#define MSG_SB_BUTTON_REDO 1050
#define MSG_SB_BUTTON_START_QUERY 1051
#define MSG_SB_BUTTON_STOP_QUERY 1052
#define MSG_SB_BUTTON_CONNECT_DB 1053
#define MSG_SB_BUTTON_DISCONNECT_DB 1054
#define MSG_DISCONNECT_FROM_DB 1055
#define MSG_ERR_OUTOFMEM 1056
#define MSG_NOT_CONNECTED 1057
#define MSG_CONNECTED 1058
#define MSG_QUERY_DONE 1059
#define MSG_QUERY_CHANGED 1060
#define MSG_STARTING_QUERY 1061
#define MSG_STOPPING_QUERY 1062
#define MSG_ERROR_READING_FILE 1063
#define MSG_ERROR_MENU 1064
#define MSG_ERROR_LOCKWB 1065
#define MSG_ERROR_CLIPBOARD 1066
#define MSG_ASL_OPENFILE 1067
#define MSG_ASL_SAVEFILE 1068
#define MSG_ASL_FILEEXISTS 1069
#define MSG_STS_STATUS_HI 1070
#define MSG_STS_DBNAME_HI 1071
#define MSG_STS_CONNSTATUS_HI 1072
#define MSG_STS_CURRENTUSER_HI 1073
#define MSG_STS_CURX_HI 1074
#define MSG_STS_CURY_HI 1075
#define MSG_STS_TEXTCHANGED_HI 1076
#define MSG_RESULTTYPE_TABLES 1077
#define MSG_RESULTTYPE_VIEWS 1078
#define MSG_RESULTTYPE_SYSTABLES 1079
#define MSG_RESULTTYPE_ALL 1080
#define MSG_RESULTS_FILENAME 1081
#define MSG_ROWS_RETURNED 1082
#define MSG_ERROR_NOMEMFORQUERY 1083

#endif /* CATCOMP_NUMBERS */


/****************************************************************************/


#ifdef CATCOMP_STRINGS

#define MSG_ERROR_STR "SQL Manager Error"
#define MSG_OK_STR "Ok"
#define MSG_SAVE_STR "Save"
#define MSG_USE_STR "Use"
#define MSG_CANCEL_STR "Cancel"
#define MSG_ABORT_STR "Abort"
#define MSG_ADD_STR "Add"
#define MSG_REMOVE_STR "Remove"
#define MSG_SORT_STR "Sort"
#define MSG_YESNO_STR "Yes|No"
#define MSG_YESNOCANCEL_STR "Yes|No|Cancel"
#define MSG_ERROR_LOADING_ODBC_STR "Error while connecting to ODBC!"
#define MSG_CONNECT_DSN_STR "Connect to an ODBC data source"
#define MSG_SELECT_DSN_STR "Select the DSN to use"
#define MSG_ENTER_CREDENTIALS_STR "Enter the credentials to access the server"
#define MSG_USERNAME_STR "Username :"
#define MSG_PASSWORD_STR "Password :"
#define MSG_DSN_MANAGER_STR "_DSN Manager"
#define MSG_BUTTON_CONNECT_STR "_Connect"
#define MSG_BUTTON_CANCEL_STR "_Cancel"
#define MSG_ERROR_LISTING_TABLES_STR "Error when listing Database tables!"
#define MSG_ERROR_LAUNCHING_IODBC_STR "Error when launching iODBC!"
#define MSG_MENU_FILE_STR "File"
#define MSG_MENU_NEW_STR "New"
#define MSG_MENU_LOAD_FILE_STR "Load File.."
#define MSG_MENU_SAVE_STR "Save"
#define MSG_MENU_SAVE_AS_STR "Save As.."
#define MSG_MENU_ABOUT_STR "About"
#define MSG_MENU_EXIT_STR "Exit"
#define MSG_MENU_EDIT_STR "Edit"
#define MSG_MENU_UNDO_STR "Undo"
#define MSG_MENU_REDO_STR "Redo"
#define MSG_MENU_CUT_STR "Cut"
#define MSG_MENU_COPY_STR "Copy"
#define MSG_MENU_PASTE_STR "Paste"
#define MSG_MENU_QUERY_STR "Query"
#define MSG_MENU_EXECUTE_QUERY_STR "Execute Query"
#define MSG_MENU_STOP_QUERY_STR "Stop Query"
#define MSG_MENU_SHOW_RESULTS_STR "Show Results"
#define MSG_MENU_SHOW_AS_GRID_STR "as Grid"
#define MSG_MENU_SHOW_AS_TEXT_STR "as Text"
#define MSG_MENU_SAVE_AS_TEXT_STR "Save Results in a text File"
#define MSG_MENU_SAVE_AS_XML_STR "Save Results in a XML File"
#define MSG_SB_BUTTON_NEW_STR "Create a new query"
#define MSG_SB_BUTTON_OPEN_STR "Open an existent query file"
#define MSG_SB_BUTTON_SAVE_STR "Save the current query"
#define MSG_SB_BUTTON_CUT_STR "Cut"
#define MSG_SB_BUTTON_COPY_STR "Copy"
#define MSG_SB_BUTTON_PASTE_STR "Paste"
#define MSG_SB_BUTTON_UNDO_STR "Undo"
#define MSG_SB_BUTTON_REDO_STR "Redo"
#define MSG_SB_BUTTON_START_QUERY_STR "Start Query"
#define MSG_SB_BUTTON_STOP_QUERY_STR "Stop Query"
#define MSG_SB_BUTTON_CONNECT_DB_STR "Connect to Data Source"
#define MSG_SB_BUTTON_DISCONNECT_DB_STR "Disconnect from current Data Source"
#define MSG_DISCONNECT_FROM_DB_STR "Do you want to disconnect from current Data Source?"
#define MSG_ERR_OUTOFMEM_STR "Out of memory"
#define MSG_NOT_CONNECTED_STR "Not Connected"
#define MSG_CONNECTED_STR "Connected"
#define MSG_QUERY_DONE_STR "Done"
#define MSG_QUERY_CHANGED_STR "Query file has changed. Do you want to save it?"
#define MSG_STARTING_QUERY_STR "Starting query.."
#define MSG_STOPPING_QUERY_STR "Stopping query.."
#define MSG_ERROR_READING_FILE_STR "Error when reading the file!"
#define MSG_ERROR_MENU_STR "Cannot create the Menu!"
#define MSG_ERROR_LOCKWB_STR "Cannot lock workbench screen!"
#define MSG_ERROR_CLIPBOARD_STR "Clipboard data has no valid text!"
#define MSG_ASL_OPENFILE_STR "Open a Query file"
#define MSG_ASL_SAVEFILE_STR "Save a Query file"
#define MSG_ASL_FILEEXISTS_STR "File already exists! Do you want to replace it?"
#define MSG_STS_STATUS_HI_STR "Query status"
#define MSG_STS_DBNAME_HI_STR "Database name"
#define MSG_STS_CONNSTATUS_HI_STR "Connection status"
#define MSG_STS_CURRENTUSER_HI_STR "Current user"
#define MSG_STS_CURX_HI_STR "Current X cursor position"
#define MSG_STS_CURY_HI_STR "Current Y cursor position"
#define MSG_STS_TEXTCHANGED_HI_STR "This panel show if the text has changed into the query manager"
#define MSG_RESULTTYPE_TABLES_STR "Tables"
#define MSG_RESULTTYPE_VIEWS_STR "Views"
#define MSG_RESULTTYPE_SYSTABLES_STR "Sys Tables"
#define MSG_RESULTTYPE_ALL_STR "All"
#define MSG_RESULTS_FILENAME_STR "Choose the filename to save the results"
#define MSG_ROWS_RETURNED_STR "rows returned."
#define MSG_ERROR_NOMEMFORQUERY_STR "Not enough memory to execute the query!"

#endif /* CATCOMP_STRINGS */


/****************************************************************************/


#ifdef CATCOMP_ARRAY

struct CatCompArrayType
{
    LONG         cca_ID;
    CONST_STRPTR cca_Str;
};

STATIC CONST struct CatCompArrayType CatCompArray[] =
{
    {MSG_ERROR,(CONST_STRPTR)MSG_ERROR_STR},
    {MSG_OK,(CONST_STRPTR)MSG_OK_STR},
    {MSG_SAVE,(CONST_STRPTR)MSG_SAVE_STR},
    {MSG_USE,(CONST_STRPTR)MSG_USE_STR},
    {MSG_CANCEL,(CONST_STRPTR)MSG_CANCEL_STR},
    {MSG_ABORT,(CONST_STRPTR)MSG_ABORT_STR},
    {MSG_ADD,(CONST_STRPTR)MSG_ADD_STR},
    {MSG_REMOVE,(CONST_STRPTR)MSG_REMOVE_STR},
    {MSG_SORT,(CONST_STRPTR)MSG_SORT_STR},
    {MSG_YESNO,(CONST_STRPTR)MSG_YESNO_STR},
    {MSG_YESNOCANCEL,(CONST_STRPTR)MSG_YESNOCANCEL_STR},
    {MSG_ERROR_LOADING_ODBC,(CONST_STRPTR)MSG_ERROR_LOADING_ODBC_STR},
    {MSG_CONNECT_DSN,(CONST_STRPTR)MSG_CONNECT_DSN_STR},
    {MSG_SELECT_DSN,(CONST_STRPTR)MSG_SELECT_DSN_STR},
    {MSG_ENTER_CREDENTIALS,(CONST_STRPTR)MSG_ENTER_CREDENTIALS_STR},
    {MSG_USERNAME,(CONST_STRPTR)MSG_USERNAME_STR},
    {MSG_PASSWORD,(CONST_STRPTR)MSG_PASSWORD_STR},
    {MSG_DSN_MANAGER,(CONST_STRPTR)MSG_DSN_MANAGER_STR},
    {MSG_BUTTON_CONNECT,(CONST_STRPTR)MSG_BUTTON_CONNECT_STR},
    {MSG_BUTTON_CANCEL,(CONST_STRPTR)MSG_BUTTON_CANCEL_STR},
    {MSG_ERROR_LISTING_TABLES,(CONST_STRPTR)MSG_ERROR_LISTING_TABLES_STR},
    {MSG_ERROR_LAUNCHING_IODBC,(CONST_STRPTR)MSG_ERROR_LAUNCHING_IODBC_STR},
    {MSG_MENU_FILE,(CONST_STRPTR)MSG_MENU_FILE_STR},
    {MSG_MENU_NEW,(CONST_STRPTR)MSG_MENU_NEW_STR},
    {MSG_MENU_LOAD_FILE,(CONST_STRPTR)MSG_MENU_LOAD_FILE_STR},
    {MSG_MENU_SAVE,(CONST_STRPTR)MSG_MENU_SAVE_STR},
    {MSG_MENU_SAVE_AS,(CONST_STRPTR)MSG_MENU_SAVE_AS_STR},
    {MSG_MENU_ABOUT,(CONST_STRPTR)MSG_MENU_ABOUT_STR},
    {MSG_MENU_EXIT,(CONST_STRPTR)MSG_MENU_EXIT_STR},
    {MSG_MENU_EDIT,(CONST_STRPTR)MSG_MENU_EDIT_STR},
    {MSG_MENU_UNDO,(CONST_STRPTR)MSG_MENU_UNDO_STR},
    {MSG_MENU_REDO,(CONST_STRPTR)MSG_MENU_REDO_STR},
    {MSG_MENU_CUT,(CONST_STRPTR)MSG_MENU_CUT_STR},
    {MSG_MENU_COPY,(CONST_STRPTR)MSG_MENU_COPY_STR},
    {MSG_MENU_PASTE,(CONST_STRPTR)MSG_MENU_PASTE_STR},
    {MSG_MENU_QUERY,(CONST_STRPTR)MSG_MENU_QUERY_STR},
    {MSG_MENU_EXECUTE_QUERY,(CONST_STRPTR)MSG_MENU_EXECUTE_QUERY_STR},
    {MSG_MENU_STOP_QUERY,(CONST_STRPTR)MSG_MENU_STOP_QUERY_STR},
    {MSG_MENU_SHOW_RESULTS,(CONST_STRPTR)MSG_MENU_SHOW_RESULTS_STR},
    {MSG_MENU_SHOW_AS_GRID,(CONST_STRPTR)MSG_MENU_SHOW_AS_GRID_STR},
    {MSG_MENU_SHOW_AS_TEXT,(CONST_STRPTR)MSG_MENU_SHOW_AS_TEXT_STR},
    {MSG_MENU_SAVE_AS_TEXT,(CONST_STRPTR)MSG_MENU_SAVE_AS_TEXT_STR},
    {MSG_MENU_SAVE_AS_XML,(CONST_STRPTR)MSG_MENU_SAVE_AS_XML_STR},
    {MSG_SB_BUTTON_NEW,(CONST_STRPTR)MSG_SB_BUTTON_NEW_STR},
    {MSG_SB_BUTTON_OPEN,(CONST_STRPTR)MSG_SB_BUTTON_OPEN_STR},
    {MSG_SB_BUTTON_SAVE,(CONST_STRPTR)MSG_SB_BUTTON_SAVE_STR},
    {MSG_SB_BUTTON_CUT,(CONST_STRPTR)MSG_SB_BUTTON_CUT_STR},
    {MSG_SB_BUTTON_COPY,(CONST_STRPTR)MSG_SB_BUTTON_COPY_STR},
    {MSG_SB_BUTTON_PASTE,(CONST_STRPTR)MSG_SB_BUTTON_PASTE_STR},
    {MSG_SB_BUTTON_UNDO,(CONST_STRPTR)MSG_SB_BUTTON_UNDO_STR},
    {MSG_SB_BUTTON_REDO,(CONST_STRPTR)MSG_SB_BUTTON_REDO_STR},
    {MSG_SB_BUTTON_START_QUERY,(CONST_STRPTR)MSG_SB_BUTTON_START_QUERY_STR},
    {MSG_SB_BUTTON_STOP_QUERY,(CONST_STRPTR)MSG_SB_BUTTON_STOP_QUERY_STR},
    {MSG_SB_BUTTON_CONNECT_DB,(CONST_STRPTR)MSG_SB_BUTTON_CONNECT_DB_STR},
    {MSG_SB_BUTTON_DISCONNECT_DB,(CONST_STRPTR)MSG_SB_BUTTON_DISCONNECT_DB_STR},
    {MSG_DISCONNECT_FROM_DB,(CONST_STRPTR)MSG_DISCONNECT_FROM_DB_STR},
    {MSG_ERR_OUTOFMEM,(CONST_STRPTR)MSG_ERR_OUTOFMEM_STR},
    {MSG_NOT_CONNECTED,(CONST_STRPTR)MSG_NOT_CONNECTED_STR},
    {MSG_CONNECTED,(CONST_STRPTR)MSG_CONNECTED_STR},
    {MSG_QUERY_DONE,(CONST_STRPTR)MSG_QUERY_DONE_STR},
    {MSG_QUERY_CHANGED,(CONST_STRPTR)MSG_QUERY_CHANGED_STR},
    {MSG_STARTING_QUERY,(CONST_STRPTR)MSG_STARTING_QUERY_STR},
    {MSG_STOPPING_QUERY,(CONST_STRPTR)MSG_STOPPING_QUERY_STR},
    {MSG_ERROR_READING_FILE,(CONST_STRPTR)MSG_ERROR_READING_FILE_STR},
    {MSG_ERROR_MENU,(CONST_STRPTR)MSG_ERROR_MENU_STR},
    {MSG_ERROR_LOCKWB,(CONST_STRPTR)MSG_ERROR_LOCKWB_STR},
    {MSG_ERROR_CLIPBOARD,(CONST_STRPTR)MSG_ERROR_CLIPBOARD_STR},
    {MSG_ASL_OPENFILE,(CONST_STRPTR)MSG_ASL_OPENFILE_STR},
    {MSG_ASL_SAVEFILE,(CONST_STRPTR)MSG_ASL_SAVEFILE_STR},
    {MSG_ASL_FILEEXISTS,(CONST_STRPTR)MSG_ASL_FILEEXISTS_STR},
    {MSG_STS_STATUS_HI,(CONST_STRPTR)MSG_STS_STATUS_HI_STR},
    {MSG_STS_DBNAME_HI,(CONST_STRPTR)MSG_STS_DBNAME_HI_STR},
    {MSG_STS_CONNSTATUS_HI,(CONST_STRPTR)MSG_STS_CONNSTATUS_HI_STR},
    {MSG_STS_CURRENTUSER_HI,(CONST_STRPTR)MSG_STS_CURRENTUSER_HI_STR},
    {MSG_STS_CURX_HI,(CONST_STRPTR)MSG_STS_CURX_HI_STR},
    {MSG_STS_CURY_HI,(CONST_STRPTR)MSG_STS_CURY_HI_STR},
    {MSG_STS_TEXTCHANGED_HI,(CONST_STRPTR)MSG_STS_TEXTCHANGED_HI_STR},
    {MSG_RESULTTYPE_TABLES,(CONST_STRPTR)MSG_RESULTTYPE_TABLES_STR},
    {MSG_RESULTTYPE_VIEWS,(CONST_STRPTR)MSG_RESULTTYPE_VIEWS_STR},
    {MSG_RESULTTYPE_SYSTABLES,(CONST_STRPTR)MSG_RESULTTYPE_SYSTABLES_STR},
    {MSG_RESULTTYPE_ALL,(CONST_STRPTR)MSG_RESULTTYPE_ALL_STR},
    {MSG_RESULTS_FILENAME,(CONST_STRPTR)MSG_RESULTS_FILENAME_STR},
    {MSG_ROWS_RETURNED,(CONST_STRPTR)MSG_ROWS_RETURNED_STR},
    {MSG_ERROR_NOMEMFORQUERY,(CONST_STRPTR)MSG_ERROR_NOMEMFORQUERY_STR},
};

#endif /* CATCOMP_ARRAY */


/****************************************************************************/



#endif /* SQLMANAGER_CAT_H */
